development:
  adapter: postgresql
  encoding: utf8
  database: hartltwitter_development
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: hartltwitter_test
  host: localhost
